### ISSUE TITLE
Buggy diagram width/height

### ISSUE THREAD

**Issue by akfish** [tmtk75/jumly#31]
## Test Setup

Bugs described in this issue are usually hard to notice. I stumped upon them when using style:

``` css
// This code is in Less
.box-shadow (@color: #000, @x: 0, @y: 0, @blur: 1px, @spread, @secondary...) {
  -moz-box-shadow: @color @x @y @blur @spread, @secondary;
  -webkit-box-shadow: @color @x @y @blur @spread, @secondary;
  box-shadow: @color @x @y @blur @spread, @secondary;
}

.diagram {
     background-color: white;
     margin: 10px;
     padding: 10px;
     .box-shadow(rgba(0, 0, 0, 0.2), 0, 0, 0, 1px, rgba(0, 0, 0, 0.45), 0, 3px, 10px);
}
```

All tests are done in Chrome 33
## Case 1 - Problem with padding

This happens with robustness diagram.

Code:

``` coffee
@actor "User" :-> @view "Browser"
@view "Browser" :-> @controller "Server"
@controller "Server" :-> @entity "Database"
```

Result when padding: 10px

![image](https://f.cloud.github.com/assets/922715/2434952/38db5a50-adbd-11e3-8bec-7cbdad26c4bd.png)

The behavior is inconsistent in different cases:
- padding-top = padding-bottom = 10px

![image](https://f.cloud.github.com/assets/922715/2434978/90b4818e-adbd-11e3-9348-731df44d56c6.png)
- padding-top (= 5px) < padding-bottom (= 10px)
  ![image](https://f.cloud.github.com/assets/922715/2435050/006c1f40-adbf-11e3-81af-8ea547b1cbcb.png)
- padding-top (= 10px) > padding-bottom (= 5px)
  ![image](https://f.cloud.github.com/assets/922715/2435058/2b2ff990-adbf-11e3-9423-2cd3e6db0477.png)
- No padding (for reference)
  ![image](https://f.cloud.github.com/assets/922715/2435078/851f036a-adbf-11e3-82fc-6d6b38c59805.png)
## Case 2 - Problem with shadows

No padding:

![image](https://f.cloud.github.com/assets/922715/2435085/96cbab0e-adbf-11e3-80f0-31939843ad1f.png)

As you can see, sequence diagram and robustness diagram have different behaviors. The former one didn't take account of shadows when calculating width.
## Case 3 - Problem with custom styling

Code:

``` coffee
@found "Browser", ->
  @alt {
    "[200]": -> @message "GET href resources", "HTTP Server"
    "[301]": -> @ref "GET the moved page"
    "[404]": -> @ref "show NOT FOUND"
  }
@find(".ref").css(width:256, "padding-bottom":4)
  .find(".tag").css float:"left"
get_the_moved_page.css "background-color":"#80c080"
show_not_found.css "background-color":"#f0b0b0"
```

No padding:

![image](https://f.cloud.github.com/assets/922715/2435110/25ec151c-adc0-11e3-8b1f-bbccc9a52bbb.png)

It looks like that the size is calculated before custom styling is done. 

![image](https://f.cloud.github.com/assets/922715/2435111/350d6636-adc0-11e3-9a14-12d151182276.png)
